name: ESLint
on: [push, pull_request]
jobs: 
  build:
    defaults:
        run:
          working-directory: web/src/main/javascript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v2
        with:
          node-version: 20.12.2
      - name: Install node modules
        run: cd web/src/main/javascript && npm install
      - name: Run ESLint
        run: cd web/src/main/javascript && npm run lint