name: Frontend CI
on: [push, pull_request]
jobs: 
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web/src/main/javascript
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v2
        with:
          node-version: 20.12.2
      - name: Install node modules
        run: npm install
      - name: Build frontend
        run: npm run build
      - name: Run unit tests
        run: npm test